.MODEL SMALL
.STACK 100
.DATA 
DATA1 DW 36  ; YOU CAN CHANGE THESE VALUES ACCORDING TO YOUR DATA
DATA2 DW 60
RESULT DW ?
 
.CODE
MOV AX, @DATA          
MOV DS,AX  
MOV AX,DATA1
MOV BX,DATA2     

AGAIN: CMP AX,BX  ; IF AX>BX = IF DATA1>DATA2
JA LABEL1  ; IF YES,GO TO LABEL1
JNA LABEL2 ; IF NOT, GO TO LABEL2

LABEL1: 
SUB AX,BX   ; AX = AX-BX -> DATA1= DATA1-DATA2
     
LABEL2: 
SUB BX,AX  ; BX = BX-AX
     
CMP AX,BX  ;  IF AX>BX = IF DATA1>DATA2
JNE AGAIN     ; IF NOT EQUAL=JNE
MOV DX,AX  ; MOVE RESULT FROM AX TO DX
MOV RESULT,DX ; STORE RESULT 
MOV AX,4C00H
INT 21H
END
